version: '2.23'
networks:
  tgnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/24
          gateway: 10.10.1.1
services:
  tgtrader-testnet:
    image: tgtrader-testnet
    build:
      no_cache: false
      context: .
      platforms:
        - "linux/amd64"
      target: tgtrader-testnet
      dockerfile: ./TGtrader/DockerfileTestnet
    container_name: tgtrader-testnet
    stop_signal: SIGINT
    environment:
      FLASK_DEBUG: 0
      PWD: /TGtrader
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      tgnet:
        ipv4_address: 10.10.1.50
    ports:
      - 5000:5000
    volumes:
      - ./TGtrader:/TGtrader
  tgclient-testnet:
    image: tgclient-testnet
    build:
      no_cache: false
      context: .
      platforms:
        - "linux/amd64"
      target: tgclient-testnet
      dockerfile: ./TGclient/DockerfileTestnet
    depends_on:
      - tgtrader-testnet
    container_name: tgclient-testnet
    stop_signal: SIGINT
    environment:
      PWD: /TGclient
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      tgnet:
        ipv4_address: 10.10.1.51
    volumes:
      - ./TGclient:/TGclient
